import { NgZone, OnInit, OnDestroy } from '@angular/core';
import { EventEmitter, ElementRef } from '@angular/core';
import { SwiperDirective } from './swiper.directive';
import { SwiperConfig, SwiperConfigInterface } from './swiper.interfaces';
export declare class SwiperComponent implements OnInit, OnDestroy {
    private zone;
    private elementRef;
    private defaults;
    private mo;
    private paginationBulletRender;
    index: number;
    fxShow: boolean;
    fxHide: boolean;
    hidden: boolean;
    disabled: boolean;
    config: SwiperConfigInterface;
    useSwiperClass: boolean;
    runInsideAngular: boolean;
    useSwiperWrapperClass: boolean;
    indexChange: EventEmitter<number>;
    swiperSlides: ElementRef;
    directiveRef: SwiperDirective;
    readonly isAtLast: boolean;
    readonly isAtFirst: boolean;
    S_INIT: EventEmitter<any>;
    S_DESTROY: EventEmitter<any>;
    S_SCROLL: EventEmitter<any>;
    S_PROGRESS: EventEmitter<any>;
    S_SETTRANSLATE: EventEmitter<any>;
    S_SETTRANSITION: EventEmitter<any>;
    S_AUTOPLAY: EventEmitter<any>;
    S_AUTOPLAYSTART: EventEmitter<any>;
    S_AUTOPLAYSTOP: EventEmitter<any>;
    S_REACHBEGINNING: EventEmitter<any>;
    S_REACHEND: EventEmitter<any>;
    S_SLIDECHANGESTART: EventEmitter<any>;
    S_SLIDECHANGEEND: EventEmitter<any>;
    S_SLIDENEXTSTART: EventEmitter<any>;
    S_SLIDENEXTEND: EventEmitter<any>;
    S_SLIDEPREVSTART: EventEmitter<any>;
    S_SLIDEPREVEND: EventEmitter<any>;
    S_SLIDERMOVE: EventEmitter<any>;
    S_CLICK: EventEmitter<any>;
    S_TAP: EventEmitter<any>;
    S_DOUBLETAP: EventEmitter<any>;
    S_TOUCHSTART: EventEmitter<any>;
    S_TOUCHMOVE: EventEmitter<any>;
    S_TOUCHMOVEOPPOSITE: EventEmitter<any>;
    S_TOUCHEND: EventEmitter<any>;
    S_TRANSITIONSTART: EventEmitter<any>;
    S_TRANSITIONEND: EventEmitter<any>;
    S_IMAGESREADY: EventEmitter<any>;
    S_LAZYIMAGELOAD: EventEmitter<any>;
    S_LAZYIMAGEREADY: EventEmitter<any>;
    S_PAGINATIONRENDERED: EventEmitter<any>;
    constructor(zone: NgZone, elementRef: ElementRef, defaults: SwiperConfig);
    ngOnInit(): void;
    ngOnDestroy(): void;
    getConfig(): SwiperConfig;
    updateClasses(): void;
    update(updateTranslate?: boolean): void;
    getIndex(): any;
    setIndex(index: number, speed?: number, callbacks?: boolean): void;
    prevSlide(callbacks?: boolean, speed?: number): void;
    nextSlide(callbacks?: boolean, speed?: number): void;
    stopAutoplay(): void;
    startAutoplay(): void;
}
