import { NgZone, SimpleChanges, KeyValueDiffers } from '@angular/core';
import { OnInit, DoCheck, OnDestroy, OnChanges } from '@angular/core';
import { EventEmitter, ElementRef } from '@angular/core';
import { SwiperConfig, SwiperConfigInterface } from './swiper.interfaces';
export declare class SwiperDirective implements OnInit, DoCheck, OnDestroy, OnChanges {
    private zone;
    private elementRef;
    private differs;
    private defaults;
    swiper: any;
    private configDiff;
    private initialIndex;
    index: number;
    fxShow: boolean;
    fxHide: boolean;
    hidden: boolean;
    disabled: boolean;
    useSwiperClass: boolean;
    runInsideAngular: boolean;
    config: SwiperConfigInterface;
    indexChange: EventEmitter<number>;
    S_INIT: EventEmitter<any>;
    S_DESTROY: EventEmitter<any>;
    S_SCROLL: EventEmitter<any>;
    S_PROGRESS: EventEmitter<any>;
    S_SETTRANSLATE: EventEmitter<any>;
    S_SETTRANSITION: EventEmitter<any>;
    S_AUTOPLAY: EventEmitter<any>;
    S_AUTOPLAYSTART: EventEmitter<any>;
    S_AUTOPLAYSTOP: EventEmitter<any>;
    S_REACHBEGINNING: EventEmitter<any>;
    S_REACHEND: EventEmitter<any>;
    S_SLIDECHANGESTART: EventEmitter<any>;
    S_SLIDECHANGEEND: EventEmitter<any>;
    S_SLIDENEXTSTART: EventEmitter<any>;
    S_SLIDENEXTEND: EventEmitter<any>;
    S_SLIDEPREVSTART: EventEmitter<any>;
    S_SLIDEPREVEND: EventEmitter<any>;
    S_SLIDERMOVE: EventEmitter<any>;
    S_CLICK: EventEmitter<any>;
    S_TAP: EventEmitter<any>;
    S_DOUBLETAP: EventEmitter<any>;
    S_TOUCHSTART: EventEmitter<any>;
    S_TOUCHMOVE: EventEmitter<any>;
    S_TOUCHMOVEOPPOSITE: EventEmitter<any>;
    S_TOUCHEND: EventEmitter<any>;
    S_TRANSITIONSTART: EventEmitter<any>;
    S_TRANSITIONEND: EventEmitter<any>;
    S_IMAGESREADY: EventEmitter<any>;
    S_LAZYIMAGELOAD: EventEmitter<any>;
    S_LAZYIMAGEREADY: EventEmitter<any>;
    S_PAGINATIONRENDERED: EventEmitter<any>;
    constructor(zone: NgZone, elementRef: ElementRef, differs: KeyValueDiffers, defaults: SwiperConfig);
    ngOnInit(): void;
    ngDoCheck(): void;
    ngOnDestroy(): void;
    ngOnChanges(changes: SimpleChanges): void;
    update(updateTranslate?: boolean): void;
    getIndex(): any;
    setIndex(index: number, speed?: number, silent?: boolean): void;
    prevSlide(speed?: number, silent?: boolean): void;
    nextSlide(speed?: number, silent?: boolean): void;
    stopAutoplay(reset?: boolean): void;
    startAutoplay(reset?: boolean): void;
}
